using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class SimpleEffect : GameObject
	{
		#region AUTO-GENERATED BY WHISKEY2D. DO NOT EDIT. (please)
		public String Effect { get; set; } 
		public Vector Frames { get; set; } 
		public Int32 Speed { get; set; } 
		public Boolean LightLayer { get; set; } 

		#region INIT_VALUE_ASSIGNMENT
		protected override void initProperties()
		{
			X = 0f;
			Y = 0f;
			Sprite = new Sprite("__PIXEL__", new Vector(1f, 1f), new Vector(0f, 0f), 0.5f, new Color(255, 255, 255, 255), 0f);
			Light = new Light(new Vector(0f, 0f), new Color(255, 255, 255, 255), 512f, false);
			Shadows = new ShadowProperties(false, true, false, 1f, 100f);
			Name = "???";
			Active = true;
			HudObject = false;
			IsDebug = false;
			Effect = "0";
			Frames = new Vector(1f, 1f);
			Speed = 7;
			LightLayer = false;
		}
		#endregion

		public SimpleEffect( ObjectManager objMan ) : base (objMan) { }
		#region INIT_SCRIPTS
		protected override void addInitialScripts()
		{
			base.addScript( new EffectControl() );
		}
		#endregion

		#endregion END OF AUTO-GENERATED CODE.

		public override void initializeObject()
		{
			//implement your code here!
			RadiusCalculator = (n) => { return Light.Radius; };
		}

		public RadiusFunction RadiusCalculator {get; set;}
		public delegate float RadiusFunction(int frameNumber);


	}
}






