using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class SoundArea : GameObject
	{
		#region AUTO-GENERATED BY WHISKEY2D. DO NOT EDIT. (please)
		public String Sound { get; set; } 
		public String Tripee { get; set; } 
		public Boolean OnEnter { get; set; } 
		public Boolean OnExit { get; set; } 
		public Int32 PlayCount { get; set; } 
		public Boolean Loop { get; set; } 

		#region INIT_VALUE_ASSIGNMENT
		protected override void initProperties()
		{
			X = 0f;
			Y = 0f;
			Sprite = new Sprite("__PIXEL__", new Vector(1f, 1f), new Vector(0f, 0f), 0.2f, new Color(0, 0, 255, 128), 0f);
			Light = new Light(new Vector(0f, 0f), new Color(255, 255, 255, 255), 512f, false);
			Shadows = new ShadowProperties(false, true, false, 1f, 100f);
			Name = "???";
			Active = true;
			HudObject = false;
			IsDebug = true;
			Sound = "";
			Tripee = "";
			OnEnter = true;
			OnExit = false;
			PlayCount = 1;
			Loop = false;
		}
		#endregion

		public SoundArea( ObjectManager objMan ) : base (objMan) { }
		#region INIT_SCRIPTS
		protected override void addInitialScripts()
		{
		}
		#endregion

		#endregion END OF AUTO-GENERATED CODE.

		public override void initializeObject()
		{
			//implement your code here!
		}

	}
}

