using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class Tracer : GameObject
	{
		#region AUTO-GENERATED BY WHISKEY2D. DO NOT EDIT. (please)
		public Int32 Decay { get; set; } 
		public Vector Dir { get; set; } 
		public Single Speed { get; set; } 

		#region INIT_VALUE_ASSIGNMENT
		protected override void initProperties()
		{
			X = 0f;
			Y = 0f;
			Sprite = new Sprite("Tracer.png", new Vector(1f, 1f), new Vector(0f, 0f), 0.5f, new Color(255, 255, 255, 128), 0f);
			Light = new Light(new Vector(0f, 0f), new Color(255, 255, 255, 255), 512f, false);
			Shadows = new ShadowProperties(false, true, false, 1f, 100f);
			Name = "???";
			Active = true;
			HudObject = false;
			IsDebug = false;
			Decay = 9;
			Dir = new Vector(1f, 1f);
			Speed = 0f;
		}
		#endregion

		public Tracer( ObjectManager objMan ) : base (objMan) { }
		#region INIT_SCRIPTS
		protected override void addInitialScripts()
		{
			base.addScript( new TracerFade() );
		}
		#endregion

		#endregion END OF AUTO-GENERATED CODE.

		public override void initializeObject()
		{
			//implement your code here!
		}


		public override void renderLight(RenderInfo info){
		
			Sprite.draw(info.SpriteBatch, info.Transform, Position);
			Light.Color = Color.Black;
			base.renderLight(info);
		}

	}
}




