using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class BadguyControl : Script<Badguy>
	{
	
		Player plr;
		Vector surface = Vector.Zero;
		bool jumping = false;
		
		
		public override void onStart()
		{

			plr = Objects.getObject<Player>("Player");

		}
		
		public override void onUpdate() 
		{

			
			Vector gravity = new Vector(0, 2);
			Vector acc = Vector.Zero;
			Vector friction = new Vector(.08f, 0);
			
			
			if (( plr.Position - Gob.Position).Length < 1400){
				bool isPlayerOnRight = (plr.X - Gob.X) > 0;
				if (isPlayerOnRight){
					acc += Vector.UnitX * .3f;
				} else acc -= Vector.UnitX * .3f ;
				
				if (surface.Y > .8f){
					jumping = true;
					acc -= gravity * 10;
				}
			
			}
			
			acc += gravity;
		
			Gob.Velocity += acc;
			
			
			Gob.Velocity -= new Vector(Gob.Velocity.X * friction.X, Gob.Velocity.Y * friction.Y);
			
			
			Gob.Position += Gob.Velocity;
			
			Collisions<Wall> wallColls = Gob.currentCollisions<Wall>();
			
			surface = Vector.Zero;
			foreach (Collision<Wall> c in wallColls){
				Gob.Position -= c.MTV;
				
				Gob.Velocity = c.Normal.Perpendicular * c.Normal.Perpendicular.dot(Gob.Velocity);
				
				if (c.Normal.Y > .8f){
					surface = c.Normal;
				
					jumping = false;
				}
			}


		

		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}






















