using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class EffectControl : Script<SimpleEffect>
	{
	
		Animation a;
	
		public override void onStart()
		{
		 
		 	Gob.Sprite.ImagePath = Gob.Effect + ".png";
		 	Gob.Sprite.Rows = (int)Gob.Frames.X;
		 	Gob.Sprite.Columns = (int)Gob.Frames.Y;
		 	
		 	a = Gob.Sprite.createAnimation(0, Gob.Sprite.FrameCount, Gob.Speed, false);
		}
		
		public override void onUpdate() 
		{
		 //This code runs when the GameObject is updated
		 	a.advanceFrame();
		 	Gob.Light.Radius = Gob.RadiusCalculator(a.CurrentFrame);
		 	if (a.CurrentFrame == a.EndFrame){
		 		Gob.close();
		 	}
		 	
		 	
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}











