using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class ExplosionScript : Script<Explosion>
	{
		Animation a;
		public override void onStart()
		{
		 
		 	a = Gob.Sprite.createAnimation(0, 20, 2, false);
		 
		 
		}
		
		public override void onUpdate() 
		{
		 
		 	a.advanceFrame();
		 
		 
		 
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}









