using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class Musical : Script<SimpleObject>
	{
	
		Sound s;
	
		public override void onStart()
		{
			s = new Sound("W2DDemo.wav");
			s.play();
		}
		
		public override void onUpdate() 
		{
		 //This code runs when the GameObject is updated
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}




