using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class ParallaxControl : Script<Parallax>
	{
	
		GameObject target;
		Vector targetStart = Vector.Zero;
		Vector gobStart = Vector.Zero;
		
		public override void onStart()
		{

			target = Objects.getObject(Gob.Target);
			if (target != null){
				targetStart = target.Position;
				gobStart = Gob.Position;
			
			}


		}
		
		public override void onUpdate() 
		{
		 
		 	if (target != null){
		 	
		 		Gob.X = gobStart.X + Gob.Sprite.Depth * Gob.Sprite.Depth * (targetStart.X - target.X);
		 	
		 	}
		 
		 
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}







