using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class PlayerAnimator : Script<Player>
	{
	
	
		SimpleObject vis;
		
		Animation runLeft;
		Animation runRight;
		
	
		public override void onStart()
		{

			vis = new SimpleObject(Level);
			vis.Sprite.ImagePath = "W2Drun2.png";
			vis.Sprite.Columns = 8;
			vis.Sprite.Rows = 2;
			vis.Sprite.Scale = Vector.One * .6f;
			
			runLeft = vis.Sprite.createAnimation(8, 15, 7, true);
			runRight = vis.Sprite.createAnimation(0, 7, 7, true);
			
			
		}
		
		public override void onUpdate() 
		{

			vis.Position = Gob.Position;

			if ( Math.Abs(Gob.Velocity.Y) < .1f){		
				if (Gob.Acceleration.X > 0){
					runRight.advanceFrame();
				}
				if (Gob.Acceleration.X < 0){
					runLeft.advanceFrame();
				}
			}
		

		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}














