using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class PlayerMove : Script<Player>
	{
		Vector surface = Vector.Zero;
		bool jumping = false;
		int jumpCounter = 0;
		Vector gravity = Vector.UnitY * 2;
		
		public override void onStart()
		{
		 //This code runs when the GameObject is initialized
		}
		
		public override void onUpdate() 
		{
			//Config conf = Objects.getObject<Config>("Config");
			
			
			Vector acc = Vector.Zero;
			Vector friction = new Vector(.08f, 0);
			
			if (Input.isKeyDown(Keys.A)){
				acc -= Vector.UnitX;
			}
			if (Input.isKeyDown(Keys.D)){
				acc += Vector.UnitX;
			}
			
			if (Input.isNewKeyDown(Keys.W)){
				if (surface.Y > .8f){
					jumping = true;
					jumpCounter = 50;
					acc -= gravity * 15;
					
					
					SpriteEffect fx = new SpriteEffect(Level);
					fx.Position = Gob.Position + Vector.UnitY*Gob.Bounds.Size.Y /4;
					fx.Effect = "smokeJump";
					fx.Frames = Vector.One*4;
					fx.Sprite.Scale *= .3f;
					fx.Speed = 4;
					
				}
			}
			
			
			if (Input.isKeyDown(Keys.Up)){
				if (jumping && jumpCounter > 0 ){
					acc -= gravity * .02f * jumpCounter;
					jumpCounter --;
				}
			}
		
			acc += gravity;
		
			Gob.Velocity += acc;
			
			
			Gob.Velocity -= new Vector(Gob.Velocity.X * friction.X, Gob.Velocity.Y * friction.Y);
			
			
			Gob.Position += Gob.Velocity;
			
			Collisions<Wall> wallColls = Gob.currentCollisions<Wall>();
			
			surface = Vector.Zero;
			foreach (Collision<Wall> c in wallColls){
				Gob.Position -= c.MTV;
				
				Gob.Velocity = c.Normal.Perpendicular * c.Normal.Perpendicular.dot(Gob.Velocity);
				
				if (c.Normal.Y > .8f){
					surface = c.Normal;
				
					jumping = false;
				}
			}
			
			
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}






















