using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class PlayerAnimator : Script<Player>
	{
	
	
		SimpleObject vis;
		SimpleObject arm;
		
		Animation runLeft;
		Animation runRight;
		
		Vector offset = new Vector(0, 10);
		Vector armOffset = new Vector(0, 0);
		
		public override void onStart()
		{
			Gob.Sprite.Color = new Color(1f, 1f, 0, .1f);
			vis = new SimpleObject(Level);
			vis.Sprite.ImagePath = "W2Drun2.png";
			vis.Sprite.Columns = 8;
			vis.Sprite.Rows = 2;
			vis.Sprite.Scale = Vector.One * .6f;
			
			runLeft = vis.Sprite.createAnimation(8, 15, 7, true);
			runRight = vis.Sprite.createAnimation(0, 7, 7, true);
			
			
			arm = new SimpleObject(Level);
			
			arm.Sprite.ImagePath = "W2Dgunarm.png";
			arm.Sprite.Scale = Vector.One * .6f;
			armOffset = new Vector(0, -60);
			
		}
		
		float a = 0;
		
		public override void onUpdate() 
		{
			a  = Gob.LookAngle;
			arm.Sprite.Rotation = a;
			vis.Position = Gob.Position + offset;
			
			float armShiftAngle = a + (float)Math.PI/2;
			arm.Position = Gob.Position + armOffset + (10/11f) * (arm.Sprite.ImageSize.Y /2) * new Vector( (float)Math.Cos(armShiftAngle), (float)Math.Sin(armShiftAngle));
			if ( Math.Abs(Gob.Velocity.Y) < .1f){		
				if (Gob.Acceleration.X > 0){
					runRight.advanceFrame();
					armOffset.X = 20;
				}
				if (Gob.Acceleration.X < 0){
					runLeft.advanceFrame();
					armOffset.X = -20;
				}
			}
		

		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}








































