using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class RayCastTest : Script<Player>
	{
	
		RayCollision<Wall> lastRayColl;
		SimpleObject obj;
		SimpleObject mouse;
	
		public override void onStart()
		{
		 
		 	obj = new SimpleObject(Level);
		 	mouse = new SimpleObject(Level);
		 	mouse.Sprite.Color = Color.Blue;
		}
		
		public override void onUpdate() 
		{
		 
		 	if (lastRayColl != null && lastRayColl.Gob != null){
		 		lastRayColl.Gob.Sprite.Color = Color.Black;
		 	}
		 
		 	Vector dir = Input.MouseGamePosition - Gob.Position;
		 	obj.Position = Input.MouseGamePosition;
		 	mouse.Position = obj.Position;
		 	RayCollisions<Wall> rayColls = Gob.currentRayCollisions<Wall>(dir);
		 
		 	if (rayColls.Count > 0){
		 		RayCollision<Wall> rc = rayColls[0];
		 		obj.Position = rc.ContactPoint;
		 		rc.Gob.Sprite.Color = Color.Red;
		 		lastRayColl = rc;
		 	}
		 
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}


















