using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class SoundAreaControl : Script<SoundArea>
	{
		bool active = true;
	
		bool inside = false;
		List<Sound> sounds;
		public override void onStart()
		{

			sounds = new List<Sound>();
		}
		
		public override void onUpdate() 
		{

			GameObject tripee = Objects.getObject(Gob.Tripee);
			if (tripee != null && Gob.PlayCount != 0){
				if (tripee.Bounds.boundWithin(Gob.Bounds)){
					
					
					if (!inside){
						//ON ENTER
						Gob.PlayCount --;
						Sound s = new Sound(Gob.Sound);
						s.play();
						s.Looped = Gob.Loop;
						sounds.Add(s);
					}
					
					inside = true;
				} else {
					if (inside){
						Gob.PlayCount --;
						Sound s = new Sound(Gob.Sound);
						s.Looped = Gob.Loop;
						s.play();
						sounds.Add(s);
					}
					inside =false;
				}
			}


		}
		
		public override void onClose()  
		{
		 	sounds.ForEach( s => s.stop());
		}
		
	}
}


















