using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class Tele : Script<TriggerZone>
	{
		public override void onStart()
		{
		 //This code runs when the GameObject is initialized
		}
		
		public override void onUpdate() 
		{
		 	Player p = Objects.getObject<Player>("Player");
		 	if (Gob.Bounds.boundWithin(p.Bounds)){
		 		p.Position = Objects.getObject<TriggerZone>("TeleB").Position;
		 		Level.Camera.center(p.Position);
		 	}
		 
		 
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}





