using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class ButtonControl : Script<Button>
	{
	
		Player plr;
		public override void onStart()
		{
			 plr = Objects.getObject<Player>("Player1");
		}
		
		public override void onUpdate() 
		{
			
			if (plr != null){
				if (plr.Bounds.boundWithin(Gob.Bounds)){
				
					if (Input.isNewKeyDown(Keys.Space)){
						
						Gob.Pressed = !Gob.Pressed;
						
						if (Gob.Pressed){
							ButtonControl script = getScript<ButtonControl>("DoorTester");
							Log.debug("SCRIPT = " + script);
						
							Script s = Gob.Scripts[1];
							Log.debug("SCRIPT2 = " + s);
						}
						
					}
				
				}
			}
		 	
		 	
		 	if (Gob.Pressed){
		 		Gob.Sprite.Color = Color.LimeGreen;
		 	} else {
		 		Gob.Sprite.Color = Color.Tomato;
		 	}
		 	
		 
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}















