using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class Phase2 : Script<Button>
	{
	
		CameraMaster camMaster;
		SimpleObject obj;
		DebugObject target;
		Wall wall;
		float camSpeed = 40;
		int phaseNum = 0;
	
		public override void onStart()
		{
		
		
			wall = Objects.getObject<Wall>("doorA");
		
		 	
		 	target = Objects.getObject<DebugObject>("phase2CameraSpot");
		 	
		 	camMaster = Objects.getObject<CameraMaster>("CameraMaster1");
			//camMaster.getScript("CameraMasterControl").Active = false;	
			
			obj = new SimpleObject(Level);
			obj.Position = Gob.Position;
			obj.Sprite.Color = Color.Red;
			obj.Sprite.Visible = false;
			camMaster.Target = obj.Name;
			Level.Camera.TargetZoom = .2f;
			camMaster.ObeyCamZones = false;
		
		}
		
		public override void onUpdate() 
		{
			if (target != null && obj != null){
			 	Vector toTarget = target.Position - obj.Position;
			 	Vector toTargetUnit = toTarget.UnitSafe;
			 
			 
			 	if (toTarget.Length < camSpeed * 15){
			 		Level.Camera.TargetZoom = .7f;
			 	}
			 
			 	if (toTarget.Length + 1 > camSpeed){
			 		obj.Position += toTargetUnit * camSpeed;
			 	} else {
			 		wall.Y = Math.Max(wall.Y - 5, 1200);
			 		
			 		if (wall.Y < 1201 && phaseNum == 0){
			 			target = Objects.getObject<DebugObject>("phase2CamSpotb");
		 				Level.Camera.TargetZoom = .2f;
		 				phaseNum ++;
		 				Objects.getObject<Wall>("Platform").Speed = 4;
			 			
			 		}
			 		else if (phaseNum == 1){
			 			camMaster.Target = "Player";
						Active = false;
						obj.close();
						camMaster.ObeyCamZones = true;
			 		}
			 	}
		 	}
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}















