using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class Phase1 : Script<Button>
	{
	
		WaterBlock water;
		CameraMaster camMaster;
		SimpleObject obj;
		DebugObject target;
		float camSpeed = 15;
	
		public override void onStart()
		{
		 //This code runs when the GameObject is initialized
		 	Wall wall = Objects.getObject<Wall>("WALLPIPE");
		 	wall.Active = false;
		 	wall.X = 10100;
		 	
		 	target = Objects.getObject<DebugObject>("Phase1CameraSpot");
		 	water = Objects.getObject<WaterBlock>("WaterBlock1");
		 	camMaster = Objects.getObject<CameraMaster>("CameraMaster1");
			//camMaster.getScript("CameraMasterControl").Active = false;	
			
			obj = new SimpleObject(Level);
			obj.Position = Gob.Position;
			obj.Sprite.Color = Color.Red;
			obj.Sprite.Visible = false;
			camMaster.Target = obj.Name;
			camMaster.ObeyCamZones = false;
		 	Level.Camera.TargetZoom = .55f;
		}
		
		public override void onUpdate() 
		{
		 	if (target != null && obj != null){
			 	Vector toTarget = target.Position - obj.Position;
			 	Vector toTargetUnit = toTarget.UnitSafe;
			 
			 	if (toTarget.Length + 1 > camSpeed){
			 		obj.Position += toTargetUnit * camSpeed;
			 	} else {
			 	
			 		target.Y = Math.Min(2600, target.Y + 7);
			 		camSpeed = 7;
			 		
			 		if (!water.Sink){
			 			water.Sink = true;
			 		}
			 		if (!water.Active){
			 			camMaster.Target = "Player";
						Active = false;
						obj.close();
						camMaster.ObeyCamZones = true;
						
			 		}
			 	}
			 }
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}


































