using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class Tele : Script<Button>
	{
	
		Player plr;
	
		public override void onStart()
		{
		 	plr = Objects.getObject<Player>("Player");
		 	plr.Position = new Vector(200);
		 	Level.Camera.TruePosition = plr.Position;
		 	
		 	Objects.getObject<Wall>("WALLPIPE").Active = (Objects.getObject<Wall>("doorA").Y < 1201);
		 	if (Objects.getObject<Wall>("WALLPIPE").Active){
		 		Objects.getObject<Wall>("WALLPIPE").X = 9650;
		 	}
		}
		
		public override void onUpdate() 
		{
		 	
		 	
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}





