using System;
using System.Collections.Generic;
using Whiskey2D.Core;
using Whiskey2D.Core.Managers;
using Whiskey2D.Core.Inputs;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;

//auto-generated by Whiskey2D
namespace Project
{
	[Serializable] 
	public class WallMove : Script<Wall>
	{
	
		bool goingToA;
		
	
		public override void onStart()
		{
		 
		 	goingToA = !Gob.StartOnA;
		 
		}
		
		public override void onUpdate() 
		{
		 	Vector vel;
		 	Vector target;
		 	if (goingToA){
		 		target = Gob.EndA;
		 	} else target = Gob.EndB;
		 
		 
		 	Gob.Velocity = (target - Gob.Position).UnitSafe * Gob.Speed;
		 	
		 	Gob.Position += Gob.Velocity;
		 
		 
		 
		 	if ( (Gob.Position - target).Length < Gob.Speed){
		 		goingToA = !goingToA;
		 	
		 	}
		 
		 
		 
		 
		}
		
		public override void onClose()  
		{
		 //This code runs when the GameObject is closed
		}
		
	}
}








